name: Test

on:
  pull_request:
    paths-ignore:
      - '**.md'    
  push:    
    branches:
      - master
    paths-ignore:
      - '**.md'
jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: true
      - name: Setup node 12
        uses: actions/setup-node@v2
        with:
          node-version: 12.x
      - run: yarn --frozen-lockfile
      - run: yarn codegen
      - run: yarn test
      - run: cd examples/pure && yarn --frozen-lockfile && yarn test